FROM fedora:22

RUN dnf install -y      \
    git                 \
    gnuplot             \
    libxml2-devel       \
    vtk-devel           \
    openmpi-devel       \
    log4cxx-devel       \
    boost-devel         \
    gmsh-devel          \
    gtest-devel         \
    gsl-devel           \
    boost-openmpi-devel \
    scotch-devel        \
    make                \
    cmake               \
    gcc-c++          && \
    dnf clean all
